<!doctype html>
<html>

<head>
    <title>eScriptorium Proxy API - Scalar</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
        body {
            margin: 0;
        }
    </style>
</head>

<body>
    <!-- 
      Scalar API Reference Configuration
      data-url: Points to the OpenAPI/Swagger JSON generated by Scramble
    -->
    <script id="api-reference" data-url="/docs/api.json">
    </script>

    <!-- Load Scalar via CDN -->
    <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>

</html>